version: "3.8"

services:
  postgresql:
    image: 'postgres:15.3-bullseye'
    container_name: 'demo-postgres'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demodb
    ports:
      - "5432"
    user: root
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
      - './src/test/resources/db:/docker-entrypoint-initdb.d'

volumes:
  pg_data: